CREATE DATABASE IF NOT EXISTS student CHARSET SET UTF8;
USE student;
CREATE TABLE students (
  `id` BIGINT(11) NOT NULL AUTO_INCREMENT COMMENT '唯一编号',
  `name` VARCHAR(255) DEFAULT '' COMMENT '姓名',
  `birthday` DATE DEFAULT NULL COMMENT '出生日期',
  `origin` VARCHAR(255) DEFAULT '' COMMENT '生源地',
  `gpa` DECIMAL(3,2) DEFAULT '0.00' COMMENT '绩点',
  PRIMARY KEY (`id`),
  CONSTRAINT students CHECK (gpa>=1 AND gpa<=5)
) ENGINE=INNODB DEFAULT CHARSET=utf8;